name: Lint
permissions:
  contents: read

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Lint
        run: yarn lint
      - name: Check types
        run: yarn tsc --noEmit
